//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
<<<<<<< HEAD

    public partial class ChatEntities : DbContext
    {
        public ChatEntities() : base("name=ChatEntities")
        {

        }

=======
    
    public partial class ChatEntities : DbContext
    {
        public ChatEntities()
            : base("name=ChatEntities")
        {
        }
    
>>>>>>> 6ca16eb674649a1dba8c9a59a1146192217f0063
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
<<<<<<< HEAD

=======
    
>>>>>>> 6ca16eb674649a1dba8c9a59a1146192217f0063
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
