//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatServer
{
    using System;
    using System.Collections.Generic;
<<<<<<< HEAD

=======
    
>>>>>>> 6ca16eb674649a1dba8c9a59a1146192217f0063
    public partial class Message
    {
        public int Id { get; set; }
        public int Id_user_to { get; set; }
        public int Id_user_from { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public string Message1 { get; set; }
<<<<<<< HEAD

=======
    
>>>>>>> 6ca16eb674649a1dba8c9a59a1146192217f0063
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
